mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    

mysite/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from .models import Question,Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list' : latest_question_list
    }
    return render(request, 'polls/index.html', context)
    return HttpResponse(template.render(context, request))
    output = ', '.join([q.question_text for q in latest_question_list])
    return HttpResponse(output)

def detail(request, question_id):
    return HttpResponse("Sənin sualının nömrəsi %s-dü" % question_id)
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
            })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
<title>My Blog</title>
</head>
<body style="color: white">
<h1 align="center" style="color:red">Haqqımda</h1>
<h4 style="color:black">Mənim Adım Elay-dır.10 yaşım var.6 yaşımdan proqramlaşdırmanı öyrənmək qərarını almışam.6 yaşımda "Scratch" ilə məşğul olurdum.Halhazırda "Scratch"-də 100-ə yaxın proyektim var.7 yaşımda isə "İT Step"ə daxil olmuşam.Əslində ən az 9 yaşından götürürdülər amma "Scratch" dəki proyektlərimi görüb və bir neçə dənə sual verəndən sonra götürmək qərarını aldılar.2-kursda isə sertifikat verdilər.Halhazırda 4-cü kursdayam 5-ci kursuda bitirəndə diplom verməlidirlər.7 yaşımdan sonra python dilini öyrənməyə başladım.İndi isə 10 yaşımdayam və Django-nu öyrənirəm.</h4>
<h5 style="color:black" align="center">Pythonda düzəltdiyim proyektləridə bu linklərdən gedib baxa bilərsiniz:</h5>
<li align="center"><a href="https://github.com/elay-maharramli?tab=repositories">https://github.com/elay-maharramli?tab=repositories</a>
<li align="center"><a href="https://repl.it/@Elay_Maharramli">https://repl.it/@Elay_Maharramli</a>
<img src="media/Elay.jpg" >
</body>
</html>